/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary-fixed-dim": "#a1d494",
        "on-primary-fixed-variant": "#23501e",
        "secondary-fixed": "#ffdcc3",
        "on-secondary-fixed-variant": "#6e3900",
        "inverse-primary": "#a1d494",
        "surface": "#f9faf2",
        "on-secondary": "#ffffff",
        "on-background": "#191c18",
        "on-error-container": "#93000a",
        "surface-container": "#edefe7",
        "secondary-fixed-dim": "#ffb77d",
        "on-primary": "#ffffff",
        "on-tertiary-container": "#ffaac8",
        "outline-variant": "#c2c9bb",
        "error-container": "#ffdad6",
        "error": "#ba1a1a",
        "surface-variant": "#e2e3dc",
        "secondary": "#904d00",
        "on-secondary-container": "#663500",
        "surface-tint": "#3b6934",
        "on-secondary-fixed": "#2f1500",
        "on-primary-fixed": "#002201",
        "on-surface-variant": "#42493e",
        "on-surface": "#191c18",
        "on-error": "#ffffff",
        "tertiary-container": "#7c3a55",
        "on-tertiary-fixed-variant": "#71314c",
        "tertiary": "#60233e",
        "surface-container-high": "#e7e9e1",
        "inverse-surface": "#2e312c",
        "tertiary-fixed-dim": "#ffb0cc",
        "surface-bright": "#f9faf2",
        "on-primary-container": "#9dd090",
        "on-tertiary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "primary-fixed": "#bcf0ae",
        "tertiary-fixed": "#ffd9e4",
        "primary": "#154212",
        "on-tertiary-fixed": "#3b0520",
        "background": "#f9faf2",
        "secondary-container": "#fe932c",
        "inverse-on-surface": "#f0f1ea",
        "surface-container-highest": "#e2e3dc",
        "primary-container": "#2d5a27",
        "surface-dim": "#d9dbd3",
        "outline": "#72796e",
        "surface-container-low": "#f3f4ed",
        "whatsapp": "#25D366",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        full: "9999px",
      },
      spacing: {
        xl: "32px",
        xxl: "48px",
        sm: "8px",
        "container-margin": "24px",
        gutter: "16px",
        base: "4px",
        lg: "24px",
        xs: "4px",
        md: "16px",
        "desktop-margin": "80px",
        "mobile-margin": "20px",
      },
      fontFamily: {
        "display-lg": ['"Plus Jakarta Sans"', "sans-serif"],
        "body-lg": ['"Work Sans"', "sans-serif"],
        "label-sm": ['"Work Sans"', "sans-serif"],
        "body-md": ['"Work Sans"', "sans-serif"],
        "label-md": ['"Work Sans"', "sans-serif"],
        "headline-md": ['"Plus Jakarta Sans"', "sans-serif"],
        "headline-lg-mobile": ['"Plus Jakarta Sans"', "sans-serif"],
        "headline-lg": ['"Plus Jakarta Sans"', "sans-serif"],
      },
      fontSize: {
        "display-lg": ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "1.2", fontWeight: "500" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "1.2", letterSpacing: "0.01em", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "1.3", fontWeight: "600" }],
        "headline-lg-mobile": ["28px", { lineHeight: "1.2", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "1.2", fontWeight: "700" }],
      },
      boxShadow: {
        "level-1": "0 0 0 1px rgba(0,0,0,0.04)",
        "level-2": "0 4px 12px 0 rgba(21, 66, 18, 0.08)",
        "level-3": "0 8px 24px 0 rgba(21, 66, 18, 0.12)",
      },
    },
  },
  plugins: [],
}
